# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitwit < Formula
  desc "A minimal terminal UI for git"
  homepage "https://github.com/morizkraemer/gitwit"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/morizkraemer/gitwit/releases/download/v0.1.5/gitwit_darwin_amd64.tar.gz"
      sha256 "b5677abdb17692d7d5daa7c56cb6a5c0cec711a3a3196e5cfa8154f6b125852f"

      define_method(:install) do
        bin.install "gitwit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/morizkraemer/gitwit/releases/download/v0.1.5/gitwit_darwin_arm64.tar.gz"
      sha256 "4e46eb564984d64e340e3323da7e5674c712dfbbf06a81656dd453cc57fda9a8"

      define_method(:install) do
        bin.install "gitwit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/morizkraemer/gitwit/releases/download/v0.1.5/gitwit_linux_amd64.tar.gz"
      sha256 "f00e19a8e354b6224602dd760c9100f9b7d5242370691e529e5b984fbcb4d01d"
      define_method(:install) do
        bin.install "gitwit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/morizkraemer/gitwit/releases/download/v0.1.5/gitwit_linux_arm64.tar.gz"
      sha256 "892780581d232c372c0de8255c6a75f370b9ae07a9be4977ad5b80741aba16ac"
      define_method(:install) do
        bin.install "gitwit"
      end
    end
  end
end
