# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitwit < Formula
  desc "A minimal terminal UI for git"
  homepage "https://github.com/morizkraemer/gitwit"
  version "0.1.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/morizkraemer/gitwit/releases/download/v0.1.11/gitwit_darwin_amd64.tar.gz"
      sha256 "0306938eb2e8191649aa173df98076b37c7c2a8e3982c0c5cb5d3208aae79712"

      define_method(:install) do
        bin.install "gitwit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/morizkraemer/gitwit/releases/download/v0.1.11/gitwit_darwin_arm64.tar.gz"
      sha256 "9dd213b2c33482690fe346a900a08160e442a16890653c96ee9a15f85f661bd6"

      define_method(:install) do
        bin.install "gitwit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/morizkraemer/gitwit/releases/download/v0.1.11/gitwit_linux_amd64.tar.gz"
      sha256 "6ac2434356a473d1d5ef2323719f40f3fc737b1ed9329ccb6204b2f330210b90"
      define_method(:install) do
        bin.install "gitwit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/morizkraemer/gitwit/releases/download/v0.1.11/gitwit_linux_arm64.tar.gz"
      sha256 "90f60093661f301e2711c03eaa29081918fd12a74086371ab8e6efa3ad15509a"
      define_method(:install) do
        bin.install "gitwit"
      end
    end
  end
end
